# @package _global_
dataset:
  _target_: src.data.SyntheticCancerDatasetCollection   # Will be dynamically instantiated
  name: tumor_generator
  coeff: 4                                            # Confounding coefficient (gamma)
  chemo_coeff: ${dataset.coeff}                         # Confounding coefficient of chemotherapy
  radio_coeff: ${dataset.coeff}                         # Confounding coefficient of radiotherapy
  seed: ${exp.seed}
  num_patients:
    train: 10000
    val: 1000
    test: 100
  window_size: 15                                       # Used for biased treatment assignment
  lag: 0                                                # Lag for treatment assignment window
  max_seq_length: 60                                    # Max length of time series
  projection_horizon: 5                                 # Range of tau-step-ahead prediction (tau = projection_horizon + 1)
  cf_seq_mode: sliding_treatment                        # sliding_treatment / random_trajectories
  val_batch_size: 512                                   # Batch size for evaluation
  treatment_mode: multiclass                            # multiclass / multilabel -- for RMSN

model:
  name: CT_DomainConfusion
  dim_treatments: 4
  dim_vitals: 0
  dim_static_features: 1
  dim_outcomes: 1
  
  multi:
    tune_hparams: False 
    batch_size: 128
    seq_hidden_units: 12
    br_size: 16
    fc_hidden_units: 48
    dropout_rate: 0.1
  
    _target_: src.models.ct.CT
    max_seq_length: ${sum:${dataset.max_seq_length},${dataset.projection_horizon}}  # Will be calculated dynamically
    num_layer: 1
    num_heads: 2
    max_grad_norm: 1
    attn_dropout: True
    disable_cross_attention: False
    isolate_subnetwork: _
    self_positional_encoding:
      absolute: False
      trainable: True
      max_relative_position: 15
    optimizer:
      optimizer_cls: adam
      learning_rate: 0.01
      weight_decay: 0.0
      lr_scheduler: False

    augment_with_masked_vitals: True

    tune_range: 50
    hparams_grid:
    resources_per_trial:

exp:
  unscale_rmse: True
  percentage_rmse: True
  seed: 100
  weights_ema: True
  gpus: [0]                         # Number of GPUs to use / indices of GPUs like [0,1]
  logging: True                     # Logging to MlFlow
  mlflow_uri: http://127.0.0.1:8081 # MlFlow server
  alpha: 0.01
  beta: 0.99 
  balancing: domain_confusion
  max_epochs: 150
  alpha_rate: exp
  update_alpha: False
  bce_weight: False 


# if grad_reverse:
# dataset:
#   coeff: 4.0

# model:
#   multi:
#     optimizer:
#       learning_rate: 0.001
#     batch_size: 128
#     seq_hidden_units: 16
#     br_size: 16
#     fc_hidden_units: 48
#     dropout_rate: 0.1

#   self_positional_encoding:
#     max_relative_position: 15

# exp:
#   weights_ema: False
#   alpha: 1.0
#   balancing: grad_reverse
#   max_epochs: 100
